list_stock:
- AGG
- BCE
- BCM
- CCL
- CDC
- CIG
- CKG
- CRE
- D2D
- DIG
- DRH
- DTA
- DXG
- DXS
- EVG
- FDC
- FIR
- HAR
- HDC
- HDG
- HPX
- HQC
- HU1
- IJC
- ITA
- ITC
- KBC
- KDH
- KHG
- KOS
- LDG
- LGL
- LHG
- NBB
- NHA
- NLG
- NTL
- NVL
- PDR
- PTL
- QCG
- SCR
- SGR
- SJS
- SZC
- SZL
- TCH
- TDC
- TDH
- TIP
- TIX
- TN1
- VHM
- VIC
- VPH
- VPI
- VRC
- VRE